version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    interval: "weekly"
    open-pr-limit: 5
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    interval: "weekly"
    open-pr-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "major"
